name: Check Links

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  link-checker:
    name: Check for Broken Links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check links
        uses: lycheeverse/lychee-action@v2.9.0
        with:
          args: |
            --verbose
            --no-progress
            --exclude-mail
            './README.md'
          fail: true
